# SPDX-License-Identifier: GPL-2.0+

extra-y	= start.o

obj-y += reset.o
obj-y += cpu.o
obj-y += clocks.o
obj-y += sram_init.o
obj-y += launch.o
obj-y += lowlevel_init.o
obj-y += cps.o
obj-y += launch.o
obj-y += launch_ll.o

obj-y += dramc/
obj-$(CONFIG_SPL_BUILD) += spl/
obj-$(CONFIG_MT7621_MEMTEST) += memtest/
